"use client";
import 'antd/dist/reset.css';

import {ConfigProvider, Layout} from 'antd';
import {Metadata} from "next";
const { Header, Content } = Layout;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ConfigProvider theme={{
          token: {
              colorPrimary: '#00b96b',
          },
      }}>
          <Layout>
              <Header>App Title</Header>
              <Content className="container">{children}</Content>
          </Layout>
      </ConfigProvider>
      </body>
    </html>
  )
}
